// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoSharovarshyna.Services.ProductAPI.DbContexts;

#nullable disable

namespace NeoSharovarshyna.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NeoSharovarshyna.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Soup",
                            Description = "Ukrainian traditional soup",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/a7/Borscht_served.jpg",
                            Name = "Borsch",
                            Price = 20.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "First cours",
                            Description = "Ukrainian traditional food",
                            ImageUrl = "https://f.authenticukraine.com.ua/photo/5410/qNL1g.jpg",
                            Name = "Varenyky",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Baking",
                            Description = "Ukrainian traditional bake",
                            ImageUrl = "https://tasteofartisan.com/wp-content/uploads/2019/09/Ukrainian-Pampushki-Recipe-1.jpg",
                            Name = "Pampushky",
                            Price = 3.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Sauce",
                            Description = "Ukrainian taditional sauce",
                            ImageUrl = "https://petersfoodadventures.com/wp-content/uploads/2018/08/homemade-sour-cream.jpg",
                            Name = "Smetana",
                            Price = 3.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Snack",
                            Description = "Ukrainian traditional snack",
                            ImageUrl = "https://ukrainefood.info/uploads/img/x22_52a5f2f6ce6bb.jpg",
                            Name = "Salo",
                            Price = 5.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
